# Fictitious Names

In [12]:
# import numpy as np
import pandas as pd
import numpy as np

In [13]:
# Copio esta clase por si luego quiero que me queden más bonitos los prints
class display(object):
    """Representador HTML de múltiples objetos"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

### Step 2. Create the 3 DataFrames based on the following raw data

In [14]:
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

### Step 3. Assign each to a variable called data1, data2, data3

In [15]:
# Hago el ejercicio 2 directamente con el ejercicio 3, hago los data frames con el raw data anterior, y lo guardo directamente en las variables
data1 = pd.DataFrame(raw_data_1)
data1.info() # Quiero ver que se me han importado bien los datos y los tipos de datos.

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  5 non-null      str
 1   first_name  5 non-null      str
 2   last_name   5 non-null      str
dtypes: str(3)
memory usage: 252.0 bytes

In [16]:
data2 = pd.DataFrame(raw_data_2)
data2.info() # Quiero ver que se me han importado bien los datos y los tipos de datos.

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  5 non-null      str
 1   first_name  5 non-null      str
 2   last_name   5 non-null      str
dtypes: str(3)
memory usage: 252.0 bytes

In [17]:
data3 = pd.DataFrame(raw_data_3)
data3.info() # Quiero ver que se me han importado bien los datos y los tipos de datos.

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   subject_id  10 non-null     str
 1   test_id     10 non-null     int64
dtypes: int64(1), str(1)
memory usage: 292.0 bytes

### Step 4. Join the two first dataframes along rows and assign to all_data

In [18]:
# Unir los dos primeros dataframes por medio de filas 
all_data = pd.concat([data1, data2], axis = 0).reset_index(drop=True) # con reset_index: drop = True, le digo que resetee el índice.
all_data
# Tambien se puede usar ignore_index

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
5          4      Billy    Bonder
6          5      Brian     Black
7          6       Bran   Balwner
8          7      Bryce     Brice
9          8      Betty    Btisan

In [19]:
display('data1', 'data2', "pd.concat([data1, data1], axis=0)") # Con display vemos qué dataframes usa, para concatenar y cómo los une

data1
  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

data2
  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

pd.concat([data1, data1], axis=0)
  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

### Step 5. Join the two first dataframes along columns and assing to all_data_col

In [20]:
all_data_col = pd.concat([data1, data2], axis = 1).reset_index(drop=True) # Cambio el eje para coger las columnas en vez de filas, con drop = True, le digo que elimine la columna duplicada.
all_data_col

  subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          4      Billy    Bonder
1          2        Amy  Ackerman          5      Brian     Black
2          3      Allen       Ali          6       Bran   Balwner
3          4      Alice      Aoni          7      Bryce     Brice
4          5     Ayoung   Atiches          8      Betty    Btisan

In [21]:
display('data1', 'data2', "pd.concat([data1, data1], axis=1)") # Con display vemos qué dataframes usa, para concatenar y cómo los une.

data1
  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

data2
  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

pd.concat([data1, data1], axis=1)
  subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          1       Alex  Anderson
1          2        Amy  Ackerman          2        Amy  Ackerman
2          3      Allen       Ali          3      Allen       Ali
3          4      Alice      Aoni          4      Alice      Aoni
4          5     Ayoung   Atiches          5     Ayoung   Atiches

### Step 6. Print the unique values of data3

In [22]:
data3 # Miro mi dataframe, y veo que los valores únicos en data3, están en la columna test_id. Con lo cual es la que voy a seleccionar

  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

In [23]:
print(data3["test_id"].unique()) # aquí vemos los valores únicos de la columna

[51 15 61 16 14  1]

### Step 7. Merge all_data and data3 along the subject_id value

In [24]:
data_all_data3 = pd.merge(all_data, data3, on = "subject_id") # Unión de los dos dataframes por medio de la columna subject_id.
data_all_data3

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          5     Ayoung   Atiches       16
5          4      Billy    Bonder       61
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

### Step 8. Merge only the data that has the same 'subject_id' on both data1 and data2

In [25]:
data_1y2 = pd.merge(data1, data2, on = "subject_id", how='inner') # no hace falta poner el how, pero para saber que hago un inner.
data_1y2 # Con el inner sólo coge las coincidencias, con el outer, todo de ambos y rellena los vacíos con NaNs.

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

### Step 9. Merge all values in data1 and data2, with matching records and not matching records from both sides where available.

In [ ]:
all_data1y2 = pd.merge(data1, data2,on = "subject_id", how = "outer") 
all_data1y2

# pide unir los dos dataframes tanto los valores coincidentes como los no coincidentes, por lo tanto es un outer, y me rellena los valores faltantes que no concuerdan con NaNs.

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black
5          6          NaN         NaN         Bran     Balwner
6          7          NaN         NaN        Bryce       Brice
7          8          NaN         NaN        Betty      Btisan