# Principal Components Analysis Nutrition Exercise
En este ejercicio no vas a montar ningún modelo de Machine Learning supervisado, sino aprenderás a trabajar con PCA: pretratar el dato antes de calcular sus PCs, interpretarlos, graficar y escoger número de componentes según varianza.

Importa las librerías necesarias

In [1]:
# Tratamiento de datos
# ==============================================================================
import numpy as np
import pandas as pd
import statsmodels.api as sm

# Gráficos
# ==============================================================================
import matplotlib.pyplot as plt
import matplotlib.font_manager
from matplotlib import style
style.use('ggplot') or plt.style.use('ggplot')

# Preprocesado y modelado
# ==============================================================================
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import scale

# Configuración warnings
# ==============================================================================
import warnings
warnings.filterwarnings('ignore')

### Importa los datos
1. Importa los datos: *nndb.csv*
2. Observa las columnas que hay, así como su tipo.

In [8]:
datos = pd.read_csv('data/nndb_flat.csv', index_col=0)
datos.head(10)

,FoodGroup,ShortDescrip,Descrip,CommonName,MfgName,ScientificName,Energy_kcal,Protein_g,Fat_g,Carb_g,...,Folate_USRDA,Niacin_USRDA,Riboflavin_USRDA,Thiamin_USRDA,Calcium_USRDA,Copper_USRDA,Magnesium_USRDA,Phosphorus_USRDA,Selenium_USRDA,Zinc_USRDA
ID,,,,,,,,,,,,,,,,,,,,,
1001,Dairy and Egg Products,"BUTTER,WITH SALT","Butter, salted",NaN,NaN,NaN,717.0,0.85,81.11,0.06,...,0.0075,0.002625,0.026154,0.004167,0.020000,0.000000,0.004762,0.034286,0.018182,0.008182
1002,Dairy and Egg Products,"BUTTER,WHIPPED,WITH SALT","Butter, whipped, with salt",NaN,NaN,NaN,717.0,0.85,81.11,0.06,...,0.0075,0.002625,0.026154,0.004167,0.020000,0.000018,0.004762,0.032857,0.018182,0.004545
1003,Dairy and Egg Products,"BUTTER OIL,ANHYDROUS","Butter oil, anhydrous",NaN,NaN,NaN,876.0,0.28,99.48,0.00,...,0.0000,0.000188,0.003846,0.000833,0.003333,0.000001,0.000000,0.004286,0.000000,0.000909
1004,Dairy and Egg Products,"CHEESE,BLUE","Cheese, blue",NaN,NaN,NaN,353.0,21.40,28.74,2.34,...,0.0900,0.063500,0.293846,0.024167,0.440000,0.000044,0.054762,0.552857,0.263636,0.241818
1005,Dairy and Egg Products,"CHEESE,BRICK","Cheese, brick",NaN,NaN,NaN,371.0,23.24,29.68,2.79,...,0.0500,0.007375,0.270000,0.011667,0.561667,0.000027,0.057143,0.644286,0.263636,0.236364
1006,Dairy and Egg Products,"CHEESE,BRIE","Cheese, brie",NaN,NaN,NaN,334.0,20.75,27.68,0.45,...,0.1625,0.023750,0.400000,0.058333,0.153333,0.000021,0.047619,0.268571,0.263636,0.216364
1007,Dairy and Egg Products,"CHEESE,CAMEMBERT","Cheese, camembert",NaN,NaN,NaN,300.0,19.80,24.26,0.46,...,0.1550,0.039375,0.375385,0.023333,0.323333,0.000023,0.047619,0.495714,0.263636,0.216364
1008,Dairy and Egg Products,"CHEESE,CARAWAY","Cheese, caraway",NaN,NaN,NaN,376.0,25.18,29.20,3.06,...,0.0450,0.011250,0.346154,0.025833,0.560833,0.000027,0.052381,0.700000,0.263636,0.267273
1009,Dairy and Egg Products,"CHEESE,CHEDDAR","Cheese, cheddar",NaN,NaN,NaN,406.0,24.04,33.82,1.33,...,0.0650,0.002437,0.333846,0.022500,0.562500,0.000062,0.064286,0.675714,0.514545,0.311818
1010,Dairy and Egg Products,"CHEESE,CHESHIRE","Cheese, cheshire",NaN,NaN,NaN,387.0,23.37,30.60,4.78,...,0.0450,0.005000,0.225385,0.038333,0.535833,0.000047,0.050000,0.662857,0.263636,0.253636

In [9]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8618 entries, 1001 to 93600
Data columns (total 44 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FoodGroup         8618 non-null   object
 1   ShortDescrip      8618 non-null   object
 2   Descrip           8618 non-null   object
 3   CommonName        1063 non-null   object
 4   MfgName           1560 non-null   object
 5   ScientificName    732 non-null    object
 6   Energy_kcal       8618 non-null   float64
 7   Protein_g         8618 non-null   float64
 8   Fat_g             8618 non-null   float64
 9   Carb_g            8618 non-null   float64
 10  Sugar_g           8618 non-null   float64
 11  Fiber_g           8618 non-null   float64
 12  VitA_mcg          8618 non-null   float64
 13  VitB6_mg          8618 non-null   float64
 14  VitB12_mcg        8618 non-null   float64
 15  VitC_mg           8618 non-null   float64
 16  VitE_mg           8618 non-null   float64
 17  Folate_mcg        8618 non-null   float64
 18  Niacin_mg         8618 non-null   float64
 19  Riboflavin_mg     8618 non-null   float64
 20  Thiamin_mg        8618 non-null   float64
 21  Calcium_mg        8618 non-null   float64
 22  Copper_mcg        8618 non-null   float64
 23  Iron_mg           8618 non-null   float64
 24  Magnesium_mg      8618 non-null   float64
 25  Manganese_mg      8618 non-null   float64
 26  Phosphorus_mg     8618 non-null   float64
 27  Selenium_mcg      8618 non-null   float64
 28  Zinc_mg           8618 non-null   float64
 29  VitA_USRDA        8618 non-null   float64
 30  VitB6_USRDA       8618 non-null   float64
 31  VitB12_USRDA      8618 non-null   float64
 32  VitC_USRDA        8618 non-null   float64
 33  VitE_USRDA        8618 non-null   float64
 34  Folate_USRDA      8618 non-null   float64
 35  Niacin_USRDA      8618 non-null   float64
 36  Riboflavin_USRDA  8618 non-null   float64
 37  Thiamin_USRDA     8618 non-null   float64
 38  Calcium_USRDA     8618 non-null   float64
 39  Copper_USRDA      8618 non-null   float64
 40  Magnesium_USRDA   8618 non-null   float64
 41  Phosphorus_USRDA  8618 non-null   float64
 42  Selenium_USRDA    8618 non-null   float64
 43  Zinc_USRDA        8618 non-null   float64
dtypes: float64(38), object(6)
memory usage: 3.0+ MB

In [10]:
datos.describe().T

,count,mean,std,min,25%,50%,75%,max
Energy_kcal,8618.0,226.438617,169.388910,0.0,93.000000,191.000000,336.000000,902.000000
Protein_g,8618.0,11.523910,10.550590,0.0,2.470000,8.285000,19.977500,88.320000
Fat_g,8618.0,10.647024,15.866353,0.0,0.992500,5.235000,13.900000,100.000000
Carb_g,8618.0,21.819062,27.239000,0.0,0.040000,8.945000,32.900000,100.000000
Sugar_g,8618.0,6.560253,13.602098,0.0,0.000000,0.370000,5.300000,99.800000
Fiber_g,8618.0,2.023242,4.313670,0.0,0.000000,0.300000,2.400000,79.000000
VitA_mcg,8618.0,93.968786,779.362205,0.0,0.000000,1.500000,21.000000,30000.000000
VitB6_mg,8618.0,0.264369,0.478614,0.0,0.034250,0.120000,0.355000,12.000000
VitB12_mcg,8618.0,1.225260,4.319183,0.0,0.000000,0.080000,1.297500,98.890000
VitC_mg,8618.0,7.925377,57.582758,0.0,0.000000,0.000000,2.500000,2400.000000
VitE_mg,8618.0,0.872329,3.849028,0.0,0.000000,0.110000,0.450000,149.400000
Folate_mcg,8618.0,50.306104,186.560653,0.0,0.000000,7.000000,25.000000,5881.000000
Niacin_mg,8618.0,3.411560,4.834572,0.0,0.382000,2.100000,5.029250,127.500000
Riboflavin_mg,8618.0,0.237248,0.449880,0.0,0.046000,0.150000,0.260000,17.500000
Thiamin_mg,8618.0,0.209857,0.518369,0.0,0.030000,0.077500,0.223000,23.375000
Calcium_mg,8618.0,73.411348,201.363662,0.0,9.000000,19.000000,62.000000,7364.000000
Copper_mcg,8618.0,0.172181,0.553052,0.0,0.030000,0.079000,0.144750,15.050000
Iron_mg,8618.0,2.696771,5.726967,0.0,0.530000,1.330000,2.580000,123.600000
Magnesium_mg,8618.0,32.745301,56.068454,0.0,10.000000,20.000000,29.000000,781.000000
Manganese_mg,8618.0,0.504439,6.383438,0.0,0.000000,0.022000,0.222000,328.000000
Phosphorus_mg,8618.0,155.986308,203.093234,0.0,37.000000,133.000000,216.000000,9918.000000
Selenium_mcg,8618.0,12.614945,28.292347,0.0,0.100000,3.900000,21.300000,1917.000000
Zinc_mg,8618.0,1.970216,3.358213,0.0,0.230000,0.845000,2.700000,90.950000
VitA_USRDA,8618.0,0.104410,0.865958,0.0,0.000000,0.001667,0.023333,33.333333
VitB6_USRDA,8618.0,0.155511,0.281538,0.0,0.020147,0.070588,0.208824,7.058824
VitB12_USRDA,8618.0,0.510525,1.799659,0.0,0.000000,0.033333,0.540625,41.204167
VitC_USRDA,8618.0,0.088060,0.639808,0.0,0.000000,0.000000,0.027778,26.666667
VitE_USRDA,8618.0,0.058155,0.256602,0.0,0.000000,0.007333,0.030000,9.960000
Folate_USRDA,8618.0,0.125765,0.466402,0.0,0.000000,0.017500,0.062500,14.702500
Niacin_USRDA,8618.0,0.213222,0.302161,0.0,0.023875,0.131250,0.314328,7.968750
Riboflavin_USRDA,8618.0,0.182499,0.346062,0.0,0.035385,0.115385,0.200000,13.461538
Thiamin_USRDA,8618.0,0.174881,0.431974,0.0,0.025000,0.064583,0.185833,19.479167
Calcium_USRDA,8618.0,0.061176,0.167803,0.0,0.007500,0.015833,0.051667,6.136667
Copper_USRDA,8618.0,0.000191,0.000615,0.0,0.000033,0.000088,0.000161,0.016722
Magnesium_USRDA,8618.0,0.077965,0.133496,0.0,0.023810,0.047619,0.069048,1.859524
Phosphorus_USRDA,8618.0,0.222838,0.290133,0.0,0.052857,0.190000,0.308571,14.168571
Selenium_USRDA,8618.0,0.229363,0.514406,0.0,0.001818,0.070909,0.387273,34.854545
Zinc_USRDA,8618.0,0.179111,0.305292,0.0,0.020909,0.076818,0.245455,8.268182

### Mira la correlación entre las variables numéricas
¿Qué pasa con las columnas USRDA? ¿Hay que tomar alguna decisión?

In [11]:
# Las columnas USRDA representan el porcentaje de la Cantidad Diaria Recomendada en EE. UU. (U.S. Recommended Dietary Allowance)
# Esta información no nos interesa, por lo que se eliminan
data = datos.drop(columns = datos.filter(regex='_USRDA$').columns, axis=1)
# Comprobamos que se han quitado bien
data.head(10)

,FoodGroup,ShortDescrip,Descrip,CommonName,MfgName,ScientificName,Energy_kcal,Protein_g,Fat_g,Carb_g,...,Riboflavin_mg,Thiamin_mg,Calcium_mg,Copper_mcg,Iron_mg,Magnesium_mg,Manganese_mg,Phosphorus_mg,Selenium_mcg,Zinc_mg
ID,,,,,,,,,,,,,,,,,,,,,
1001,Dairy and Egg Products,"BUTTER,WITH SALT","Butter, salted",NaN,NaN,NaN,717.0,0.85,81.11,0.06,...,0.034,0.005,24.0,0.000,0.02,2.0,0.000,24.0,1.0,0.09
1002,Dairy and Egg Products,"BUTTER,WHIPPED,WITH SALT","Butter, whipped, with salt",NaN,NaN,NaN,717.0,0.85,81.11,0.06,...,0.034,0.005,24.0,0.016,0.16,2.0,0.004,23.0,1.0,0.05
1003,Dairy and Egg Products,"BUTTER OIL,ANHYDROUS","Butter oil, anhydrous",NaN,NaN,NaN,876.0,0.28,99.48,0.00,...,0.005,0.001,4.0,0.001,0.00,0.0,0.000,3.0,0.0,0.01
1004,Dairy and Egg Products,"CHEESE,BLUE","Cheese, blue",NaN,NaN,NaN,353.0,21.40,28.74,2.34,...,0.382,0.029,528.0,0.040,0.31,23.0,0.009,387.0,14.5,2.66
1005,Dairy and Egg Products,"CHEESE,BRICK","Cheese, brick",NaN,NaN,NaN,371.0,23.24,29.68,2.79,...,0.351,0.014,674.0,0.024,0.43,24.0,0.012,451.0,14.5,2.60
1006,Dairy and Egg Products,"CHEESE,BRIE","Cheese, brie",NaN,NaN,NaN,334.0,20.75,27.68,0.45,...,0.520,0.070,184.0,0.019,0.50,20.0,0.034,188.0,14.5,2.38
1007,Dairy and Egg Products,"CHEESE,CAMEMBERT","Cheese, camembert",NaN,NaN,NaN,300.0,19.80,24.26,0.46,...,0.488,0.028,388.0,0.021,0.33,20.0,0.038,347.0,14.5,2.38
1008,Dairy and Egg Products,"CHEESE,CARAWAY","Cheese, caraway",NaN,NaN,NaN,376.0,25.18,29.20,3.06,...,0.450,0.031,673.0,0.024,0.64,22.0,0.021,490.0,14.5,2.94
1009,Dairy and Egg Products,"CHEESE,CHEDDAR","Cheese, cheddar",NaN,NaN,NaN,406.0,24.04,33.82,1.33,...,0.434,0.027,675.0,0.056,0.16,27.0,0.033,473.0,28.3,3.43
1010,Dairy and Egg Products,"CHEESE,CHESHIRE","Cheese, cheshire",NaN,NaN,NaN,387.0,23.37,30.60,4.78,...,0.293,0.046,643.0,0.042,0.21,21.0,0.012,464.0,14.5,2.79

In [ ]:
# Comprobamos que se han quitado bien
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8618 entries, 1001 to 93600
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FoodGroup       8618 non-null   object
 1   ShortDescrip    8618 non-null   object
 2   Descrip         8618 non-null   object
 3   CommonName      1063 non-null   object
 4   MfgName         1560 non-null   object
 5   ScientificName  732 non-null    object
 6   Energy_kcal     8618 non-null   float64
 7   Protein_g       8618 non-null   float64
 8   Fat_g           8618 non-null   float64
 9   Carb_g          8618 non-null   float64
 10  Sugar_g         8618 non-null   float64
 11  Fiber_g         8618 non-null   float64
 12  VitA_mcg        8618 non-null   float64
 13  VitB6_mg        8618 non-null   float64
 14  VitB12_mcg      8618 non-null   float64
 15  VitC_mg         8618 non-null   float64
 16  VitE_mg         8618 non-null   float64
 17  Folate_mcg      8618 non-null   float64
 18  Niacin_mg       8618 non-null   float64
 19  Riboflavin_mg   8618 non-null   float64
 20  Thiamin_mg      8618 non-null   float64
 21  Calcium_mg      8618 non-null   float64
 22  Copper_mcg      8618 non-null   float64
 23  Iron_mg         8618 non-null   float64
 24  Magnesium_mg    8618 non-null   float64
 25  Manganese_mg    8618 non-null   float64
 26  Phosphorus_mg   8618 non-null   float64
 27  Selenium_mcg    8618 non-null   float64
 28  Zinc_mg         8618 non-null   float64
dtypes: float64(23), object(6)
memory usage: 2.0+ MB

### Variables no numéricas
Elimina las variables de texto del dataset

In [ ]:
# Eliminar las variables de texto del dataset, quedándonos con las numéricas sólo:
df = data.select_dtypes(include=['number'])
df.head(10)

,Energy_kcal,Protein_g,Fat_g,Carb_g,Sugar_g,Fiber_g,VitA_mcg,VitB6_mg,VitB12_mcg,VitC_mg,...,Riboflavin_mg,Thiamin_mg,Calcium_mg,Copper_mcg,Iron_mg,Magnesium_mg,Manganese_mg,Phosphorus_mg,Selenium_mcg,Zinc_mg
ID,,,,,,,,,,,,,,,,,,,,,
1001,717.0,0.85,81.11,0.06,0.06,0.0,684.0,0.003,0.17,0.0,...,0.034,0.005,24.0,0.000,0.02,2.0,0.000,24.0,1.0,0.09
1002,717.0,0.85,81.11,0.06,0.06,0.0,684.0,0.003,0.13,0.0,...,0.034,0.005,24.0,0.016,0.16,2.0,0.004,23.0,1.0,0.05
1003,876.0,0.28,99.48,0.00,0.00,0.0,840.0,0.001,0.01,0.0,...,0.005,0.001,4.0,0.001,0.00,0.0,0.000,3.0,0.0,0.01
1004,353.0,21.40,28.74,2.34,0.50,0.0,198.0,0.166,1.22,0.0,...,0.382,0.029,528.0,0.040,0.31,23.0,0.009,387.0,14.5,2.66
1005,371.0,23.24,29.68,2.79,0.51,0.0,292.0,0.065,1.26,0.0,...,0.351,0.014,674.0,0.024,0.43,24.0,0.012,451.0,14.5,2.60
1006,334.0,20.75,27.68,0.45,0.45,0.0,174.0,0.235,1.65,0.0,...,0.520,0.070,184.0,0.019,0.50,20.0,0.034,188.0,14.5,2.38
1007,300.0,19.80,24.26,0.46,0.46,0.0,241.0,0.227,1.30,0.0,...,0.488,0.028,388.0,0.021,0.33,20.0,0.038,347.0,14.5,2.38
1008,376.0,25.18,29.20,3.06,0.00,0.0,271.0,0.074,0.27,0.0,...,0.450,0.031,673.0,0.024,0.64,22.0,0.021,490.0,14.5,2.94
1009,406.0,24.04,33.82,1.33,0.28,0.0,263.0,0.049,0.88,0.0,...,0.434,0.027,675.0,0.056,0.16,27.0,0.033,473.0,28.3,3.43
1010,387.0,23.37,30.60,4.78,0.00,0.0,233.0,0.074,0.83,0.0,...,0.293,0.046,643.0,0.042,0.21,21.0,0.012,464.0,14.5,2.79

In [16]:
# Comprobamos que se han quitado bien
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8618 entries, 1001 to 93600
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Energy_kcal    8618 non-null   float64
 1   Protein_g      8618 non-null   float64
 2   Fat_g          8618 non-null   float64
 3   Carb_g         8618 non-null   float64
 4   Sugar_g        8618 non-null   float64
 5   Fiber_g        8618 non-null   float64
 6   VitA_mcg       8618 non-null   float64
 7   VitB6_mg       8618 non-null   float64
 8   VitB12_mcg     8618 non-null   float64
 9   VitC_mg        8618 non-null   float64
 10  VitE_mg        8618 non-null   float64
 11  Folate_mcg     8618 non-null   float64
 12  Niacin_mg      8618 non-null   float64
 13  Riboflavin_mg  8618 non-null   float64
 14  Thiamin_mg     8618 non-null   float64
 15  Calcium_mg     8618 non-null   float64
 16  Copper_mcg     8618 non-null   float64
 17  Iron_mg        8618 non-null   float64
 18  Magnesium_mg   8618 non-null   float64
 19  Manganese_mg   8618 non-null   float64
 20  Phosphorus_mg  8618 non-null   float64
 21  Selenium_mcg   8618 non-null   float64
 22  Zinc_mg        8618 non-null   float64
dtypes: float64(23)
memory usage: 1.6 MB

### Distribuciones
Muchas de las variables tienen asimetría hacia la derecha. Deberíamos transformarlas para conseguir distribuciones normales y mejorar las correlaciones de cara al PCA y a futuros modelos lineales que vayamos a probar. Transforma todas las variables realizando una transformación Logarítmica.

### Estandarizado
Estandariza cada variable.

No es necesario que dividas en train y test.

### Implementación del PCA
Prueba a montar un PCA con todos los componentes. Para ello utiliza los datos previamente transformados y escalados.

### Aportación de cada PCA
Visualiza en un diagrama de líneas la suma acumulada de la varianza explicativa del PCA.

Si tuviéses que quedarte con 70-75 % de la varianza original, ¿con cuántos Principal Components te quedarías?

## Feat. Red
Crea un nuevo PCA con X Principal Components, siendo X la cantidad de PC escogidos en el apartado anterior.

Obtén el nuevo dataset con el mismo número de registros que el original, pero en este caso con X features, que representan los PC elegidos.

### ¿Qué grupo de comida tiene los valores más altos en cada categoría?
Determina para cada Principal Component, los 3 grupos de comida (*FoodGroup*) con los valores del PC más altos.